### ISSUE TITLE
Framebuffer DT overlay is set twice

### ISSUE THREAD

**Issue by piechade** [chirpstack/chirpstack-gateway-os#65]
There is a issue with the device tree on the latest kernel for pi 1, somewhere a framebuffer is declared twice.
My issue that i created about it: https://github.com/agherzan/meta-raspberrypi/issues/710

## Steps to reproduce this issue

Steps:

1. Build the image for pi 1
2. boot

## Log output

`/var/log/dmesg`

```shell
[    1.525659] simple-framebuffer 1e513000.framebuffer: framebuffer at 0x1e513000, 0x6d8c00 bytes, mapped to 0x(ptrval)
[    1.525749] simple-framebuffer 1e513000.framebuffer: format=a8r8g8b8, mode=1824x984x32, linelength=7296
[    1.561906] Console: switching to colour frame buffer device 228x61
[    1.594131] simple-framebuffer 1e513000.framebuffer: fb0: simplefb registered!
[    1.595147] sysfs: cannot create duplicate filename '/devices/platform/1e513000.framebuffer'
[    1.595492] CPU: 0 PID: 1 Comm: swapper Not tainted 5.4.72 #1
[    1.595707] Hardware name: BCM2835
[    1.595849] Backtrace:
[    1.596000] [<c0015860>] (dump_backtrace) from [<c0015bc4>] (show_stack+0x20/0x24)
[    1.596284]  r7:00000000 r6:cb5ded20 r5:cb522900 r4:cb4c3000
[    1.596510] [<c0015ba4>] (show_stack) from [<c080fd54>] (dump_stack+0x20/0x28)
[    1.596797] [<c080fd34>] (dump_stack) from [<c0266408>] (sysfs_warn_dup+0x60/0x74)
[    1.597086] [<c02663a8>] (sysfs_warn_dup) from [<c026655c>] (sysfs_create_dir_ns+0xec/0x10c)
[    1.597494]  r7:00000000 r6:cb522900 r5:ffffffef r4:cb5ecc10
[    1.597755] [<c0266470>] (sysfs_create_dir_ns) from [<c0815094>] (kobject_add_internal+0x90/0x308)
[    1.598084]  r6:c10633f0 r5:c10633f0 r4:cb5ecc10
[    1.598283] [<c0815004>] (kobject_add_internal) from [<c0815844>] (kobject_add+0x60/0xc4)
[    1.598582]  r9:c0b2e82c r8:c10a5000 r7:00000000 r6:c10633f0 r5:cb5ecc10 r4:00000000
[    1.598888] [<c08157e4>] (kobject_add) from [<c055d4a0>] (device_add+0x100/0x61c)
[    1.599161]  r3:00000000 r2:00000000
[    1.599315]  r6:c10633f0 r5:dbf62988 r4:cb5ecc10
[    1.599512] [<c055d3a0>] (device_add) from [<c0688f74>] (of_device_add+0x40/0x48)
[    1.599791]  r8:c10a5000 r7:00000000 r6:00000000 r5:dbf62988 r4:cb5ecc00
[    1.600048] [<c0688f34>] (of_device_add) from [<c06896fc>] (of_platform_device_create_pdata+0xb4/0xfc)
[    1.600388] [<c0689648>] (of_platform_device_create_pdata) from [<c0689764>] (of_platform_device_create+0x20/0x24)
[    1.600717]  r7:c0a25f90 r6:c114c09c r5:00000000 r4:dbf62988
[    1.600943] [<c0689744>] (of_platform_device_create) from [<c0b0f39c>] (simplefb_init+0x74/0x9c)
[    1.601244] [<c0b0f328>] (simplefb_init) from [<c000ade0>] (do_one_initcall+0x50/0x1d4)
[    1.601508]  r7:00000000 r6:c10a5000 r5:c0b2e84c r4:c0b0f328
[    1.612523] [<c000ad90>] (do_one_initcall) from [<c0add1c8>] (kernel_init_freeable+0x130/0x1f8)
[    1.623427]  r7:c0ad8e50 r6:c10a5000 r5:c0b2e84c r4:c0b5d1f8
[    1.634414] [<c0add098>] (kernel_init_freeable) from [<c08276c8>] (kernel_init+0x18/0x100)
[    1.645502]  r10:00000000 r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:c08276b0
[    1.656526]  r4:00000000
[    1.667524] [<c08276b0>] (kernel_init) from [<c00090ac>] (ret_from_fork+0x14/0x28)
[    1.678648] Exception stack(0xcb4cffb0 to 0xcb4cfff8)
[    1.689697] ffa0:                                     00000000 00000000 00000000 00000000
[    1.700961] ffc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    1.712138] ffe0: 00000000 00000000 00000000 00000000 00000013 00000000
[    1.723113]  r5:c08276b0 r4:00000000
[    1.734144] kobject_add_internal failed for 1e513000.framebuffer with -EEXIST, don't try to register things with the same name in the same directory.
```

## Your Environment

| Component             | Version |
| ----------------------| ------- |
| ChirpStack Gateway OS | v3.3.3  |

**Comment by brocaar** [comment]
@piechade does this error also occurs with the last master branch version? Because https://github.com/brocaar/chirpstack-gateway-os/commit/a958ac06742fbeec67688c684dcd54a1df4f5f41 updates the meta-raspberrypi layer:

> Submodule meta-raspberrypi updated from ac7174 to 085fb0

**Comment by piechade** [comment]
> @piechade does this error also occurs with the last master branch version? Because [a958ac0](https://github.com/brocaar/chirpstack-gateway-os/commit/a958ac06742fbeec67688c684dcd54a1df4f5f41) updates the meta-raspberrypi layer:
> 
> > Submodule meta-raspberrypi updated from ac7174 to 085fb0

Exclusively with the latest commit.

**Comment by piechade** [comment]
@brocaar something new? Can I help with something?

**Comment by brocaar** [comment]
@piechade I haven't had the time to look into this yet. As far as I know, there is no config in the ChirpStack Gateway OS recipes that defines this duplicate frame-buffer config for the Pi 1, so I think we must look into the `meta-raspberrypi` config or `u-boot` config related to the Pi 1 machine.

I will try to reproduce this asap myself on a Pi 1, but I think my guess would be as good as yours at this stage. So any help is appreciated :)

**Comment by piechade** [comment]
> @piechade I haven't had the time to look into this yet. As far as I know, there is no config in the ChirpStack Gateway OS recipes that defines this duplicate frame-buffer config for the Pi 1, so I think we must look into the `meta-raspberrypi` config or `u-boot` config related to the Pi 1 machine.
> 
> I will try to reproduce this asap myself on a Pi 1, but I think my guess would be as good as yours at this stage. So any help is appreciated :)

Did you have time to check it?

**Comment by brocaar** [comment]
Not yet, but I'm also waiting for https://github.com/openembedded/meta-openembedded/issues/285 to be resolved. Because of that issue, I can no longer build the wireguard module. According to the latest update, that issue should be fixed by this week. After that, I'll update all dependencies again.

**Comment by piechade** [comment]
@brocaar News about the issue? Is it fixed in the latest version?

**Comment by brocaar** [comment]
It was not fixed, but in the end I created a work-around  and released v3.3.3. Could you test again with this version?

**Comment by piechade** [comment]
The other issue was my fault, sorry about that.
The framebuffer error is the same as before, only the error addresses changed.

**Comment by brocaar** [comment]
I'm closing this issue as I'm not sure if it is still relevant after Yocto -> OpenWrt migration.
